name: ParkApp
description: A project for Embers Porto.

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  qr_flutter: ^1.1.3

  cached_network_image: ^0.4.2

  map_view: ^0.0.14

  geolocator: ^2.1.0

  url_launcher: ^4.0.1

  pointycastle: ^1.0.0-rc4

  asn1lib: ^0.5.3

  path_provider: ^0.4.1

  shared_preferences: ^0.4.3

  phoenix_wings: ^0.1.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - lib/assets/i18n.json
    - lib/assets/loader.gif
    - lib/assets/app_icon.png
    - lib/assets/2.0x/app_icon.png
    - lib/assets/3.0x/app_icon.png
    - lib/assets/avatar.png
    - lib/assets/2.0x/avatar.png
    - lib/assets/3.0x/avatar.png
    - lib/assets/mbway.png
    - lib/assets/2.0x/mbway.png
    - lib/assets/3.0x/mbway.png
    - lib/assets/user.png
    - lib/assets/2.0x/user.png
    - lib/assets/3.0x/user.png
    - lib/assets/home.png
    - lib/assets/2.0x/home.png
    - lib/assets/3.0x/home.png
    - lib/assets/code.png
    - lib/assets/2.0x/code.png
    - lib/assets/3.0x/code.png
    - lib/assets/height.png
    - lib/assets/2.0x/height.png
    - lib/assets/3.0x/height.png
    - lib/assets/family.png
    - lib/assets/2.0x/family.png
    - lib/assets/3.0x/family.png
    - lib/assets/bike.png
    - lib/assets/2.0x/bike.png
    - lib/assets/3.0x/bike.png
    - lib/assets/clock.png
    - lib/assets/2.0x/clock.png
    - lib/assets/3.0x/clock.png
    - lib/assets/disabled.png
    - lib/assets/2.0x/disabled.png
    - lib/assets/3.0x/disabled.png
    - lib/assets/cctv.png
    - lib/assets/2.0x/cctv.png
    - lib/assets/3.0x/cctv.png
    - lib/assets/motorcycle.png
    - lib/assets/2.0x/motorcycle.png
    - lib/assets/3.0x/motorcycle.png
    - lib/assets/park.png
    - lib/assets/2.0x/park.png
    - lib/assets/3.0x/park.png
    - lib/assets/park_steps.png
    - lib/assets/2.0x/park_steps.png
    - lib/assets/3.0x/park_steps.png
    - lib/assets/top.png
    - lib/assets/2.0x/top.png
    - lib/assets/3.0x/top.png
    - lib/assets/turn-left.png
    - lib/assets/2.0x/turn-left.png
    - lib/assets/3.0x/turn-left.png
    - lib/assets/turn-right.png
    - lib/assets/2.0x/turn-right.png
    - lib/assets/3.0x/turn-right.png
    - lib/assets/placeholder.png
    - lib/assets/2.0x/placeholder.png
    - lib/assets/3.0x/placeholder.png
    - lib/assets/car.png
    - lib/assets/2.0x/car.png
    - lib/assets/3.0x/car.png
    - lib/assets/foot.png
    - lib/assets/2.0x/foot.png
    - lib/assets/3.0x/foot.png
    - lib/assets/slight-left.png
    - lib/assets/2.0x/slight-left.png
    - lib/assets/3.0x/slight-left.png
    - lib/assets/slight-right.png
    - lib/assets/2.0x/slight-right.png
    - lib/assets/3.0x/slight-right.png
    - lib/assets/Regular-Bold.otf
    - lib/assets/Regular-Extrabold.otf
    - lib/assets/Regular-Semibold.otf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

  fonts:
    - family: Regular
      fonts:
        - asset: lib/assets/Regular-Bold.otf
        - asset: lib/assets/Regular-Extrabold.otf
        - asset: lib/assets/Regular-Semibold.otf
